export const ADMIN_CONSTANTS = {
  PRODUCTS: {
    TITLE_TOOLTIP_THRESHOLD: 50,
    DESCRIPTION_TOOLTIP_THRESHOLD: 100,
    TITLE_MAX_WIDTH: 300,
    IMAGE_SIZE: 60,
    DESCRIPTION_MAX_LINES: 2,
  },
  PAGINATION: {
    DEFAULT_PAGE: 0,
    DEFAULT_ROWS_PER_PAGE: 10,
    ROWS_PER_PAGE_OPTIONS: [5, 10, 25, 50],
  },
  DIALOG: {
    IMAGE_PREVIEW_SIZE: 150,
  },
  SNACKBAR: {
    AUTO_HIDE_DURATION: 4000,
  },
};
